/*
 * Copyright (C) 2009-2021 SAP SE or an SAP affiliate company. All rights reserved.
 */
jQuery.sap.declare("cross.fnd.fiori.inbox.annotationBasedTaskUI.util.util");cross.fnd.fiori.inbox.annotationBasedTaskUI.util.util={getBindingPath:function(u){var b="";if(u.indexOf("sid(")>=0){b=u.slice(u.indexOf("("));b=b.slice(b.indexOf("/"));}else{b=u.slice(u.lastIndexOf("/"));}return b;},getServiceUrl:function(u){var s="";if(u.indexOf("sid(")>=0){s=u.substr(0,u.indexOf(")")+1);}else{s=u.substr(0,u.indexOf("/"));}return s;},appendUrlParameter:function(u,n,v){if(!u){return u;}return u+(u.indexOf("?")<0?"?":"&")+jQuery.sap.encodeURL(n)+"="+jQuery.sap.encodeURL(v);},onTableUpdateFinished:function(e){var i=e.getParameter("total");var t=e.getSource().getHeaderToolbar().getTitleId();if(i===0){e.getSource().setVisible(false);}else{e.getSource().setVisible(true);e.getSource().getHeaderToolbar().getContent().forEach(function(c){if(c.getId()===t){var h=c.getText();h=h.substring(0,h.lastIndexOf("(")).trim();h=h+" ("+i+")";c.setText(h);}});}},getHeaderFormattedObject:function(v,c){var r="{parts : [ { path : '"+v+"'}, { path : '"+c+"'} ], type: 'sap.ui.model.type.Currency', formatOptions: {style: 'standard', showMeasure: false}}";return r;},getListItemType:function(m){return m.hasOwnProperty("com.sap.vocabularies.UI.v1.HeaderInfo")?"Navigation":"Inactive";},isNavigationProperty:function(i){return!i.hasOwnProperty("EdmType");},createFirstColumnHandledContext:function(){var m=new sap.ui.model.json.JSONModel({handled:false});return new sap.ui.model.Context(m,"/");},getMinScreenWidthAttribute:function(f){if(!f.handled){f.handled=true;return"";}return"Tablet";},cleanObject:function(o){for(var p in o){if(o.hasOwnProperty(p)){delete o[p];}}},parseEntityKeyProperties:function(e){var k={};e.forEach(function(p){var s=p.indexOf("=");if(s===-1){return null;}var P=p.substring(0,s);var v=p.substring(s+1);if(jQuery.sap.startsWith(v,"'")&&jQuery.sap.endsWith(v,"'")){v=v.substring(1,v.length-1);}k[P]=v;});return k;},standardizeEntityKey:function(m,e,E){var f="/"+e+"("+E+")",a=E.split(",");if(a.length===1&&a[0].indexOf("=")===-1){return f;}var k=this.parseEntityKeyProperties(a);if(!k){jQuery.sap.log.error("[Util] Entity keyPredicate '"+E+"' could not be parsed.");return f;}return"/"+m.createKey(e,k);},formatTableLabelText:function(t){return"<strong>"+jQuery.sap.encodeHTML(""+t)+"</strong>";},formatValueState:function(v){return sap.ui.core.ValueState[v]||sap.ui.core.ValueState.None;},hasDetails:function(v){return!!(v&&v.InboxDetails&&v.InboxDetails.AnnotationPath);}};
cross.fnd.fiori.inbox.annotationBasedTaskUI.util.formatHeaderTitle=function(i,v,a,c){var V=sap.ui.model.odata.AnnotationHelper.format(i,v);if(!a){return V;}var r=function(p){return p.substring(1,p.length-1);};var A=sap.ui.model.odata.AnnotationHelper.format(i,a);var C=sap.ui.model.odata.AnnotationHelper.format(i,c);V=r(V);A=r(A);C=r(C);var R="{parts : [{ path : '"+A+"'}, { path : '"+C+"'}, { path : '"+V+"'}]}";return R;};
cross.fnd.fiori.inbox.annotationBasedTaskUI.util.formatHeaderTitle.requiresIContext=true;
cross.fnd.fiori.inbox.annotationBasedTaskUI.util.formatHeaderNumber=function(i,v,c){var V=sap.ui.model.odata.AnnotationHelper.simplePath(i,v);var C=sap.ui.model.odata.AnnotationHelper.simplePath(i,c);V=V.replace("{","").replace("}","");C=C.replace("{","").replace("}","");var r=cross.fnd.fiori.inbox.annotationBasedTaskUI.util.util.getHeaderFormattedObject(V,C);return r;};
cross.fnd.fiori.inbox.annotationBasedTaskUI.util.formatHeaderNumber.requiresIContext=true;
cross.fnd.fiori.inbox.annotationBasedTaskUI.util.formatTableLabel=function(i,v){var p=sap.ui.model.odata.AnnotationHelper.format(i,v);if(jQuery.sap.startsWith(p,"{")&&jQuery.sap.endsWith(p,"}")){p=p.substring(0,p.length-1)+",formatter:'cross.fnd.fiori.inbox.annotationBasedTaskUI.util.util.formatTableLabelText'}";}return p;};
cross.fnd.fiori.inbox.annotationBasedTaskUI.util.formatTableLabel.requiresIContext=true;
cross.fnd.fiori.inbox.annotationBasedTaskUI.util.formatValueStateExpression=function(i,v){var p=sap.ui.model.odata.AnnotationHelper.format(i,v);if(jQuery.sap.startsWith(p,"{")&&jQuery.sap.endsWith(p,"}")){p=p.substring(0,p.length-1)+",formatter:'cross.fnd.fiori.inbox.annotationBasedTaskUI.util.util.formatValueState'}";}return p;};
cross.fnd.fiori.inbox.annotationBasedTaskUI.util.formatValueStateExpression.requiresIContext=true;
